### PR TITLE
allow changing of the default method used for Update

### PR DESCRIPTION
**Pull request by scootklein**
also added new methods to override on a per-request basis

### CODE REVIEW

**Comment by scootklein** [comment]
sorry, only the latter commit is needed for this. f87660a. 

before this gets accepted, is it currently possible to just send partial updates? the thing with PATCH even before rails announced it would be adopting it is that it existed for partial updates, and wouldn't have to send whole arrays of associations, special behavior for deleting from associations, etc. the tradeoff is, of course, multiple http calls to manage both a PATCH and a DELETE from an association (if that is the scenario you're dealing with).

it may be a better scenario to keep the `remoteUpdate` as a `PATCH` and add a new method `remoteReplace` as a `PUT` - that's really the underlying behavior.

**Comment by dingbat** [comment]
As you might know, [NSRMap](https://github.com/dingbat/nsrails/wiki/NSRMap) allows for some pretty interesting possibilities in sending attributes to Rails. This could solve your concern - simply flagging your association arrays as retrievable-only will exclude that array when sending to Rails in a create or update: `NSRMap(*, people:Person -r)`

But as this macro applies to all NSRails remote actions, I can see why a per-object, per-request selective send might be desirable. Partial updates are definitely interesting, although not yet supported. There are two ways I see it implemented:
- Having a `remoteUpdate` method that also takes an "NSRMap string" to be used temporarily for that request - this would be surprisingly easy to implement the way the code is currently structured.
- Only sending "dirtied" attributes on a `remoteUpdate`, as you mentioned in your email. Fortunately I've already written the majority of the "check for diffs" code when implementing `remoteFetch:changes:` (which lets you know if there were local changes to the object), so again, implementing a flavor `remoteUpdate` that delivers the most efficient delta should be simple enough.

I'm not sure I see the use of a `remoteReplace` right now, as it looks it's only needed in very rare cases.

**Comment by dingbat** [comment]
Also, excuse my ignorance, but GitHub is only letting me merge the entire pull request, which looks like both commits. Do you think you could submit another PR with just the one?

**Comment by scootklein** [comment]
I know it's used in rare cases, but that's really what is happening and it's why you have to send the whole object. I struggle with using a method called "update" to "place" an item on the server. 

Keep in mind that you don't need to have a previously-retrieved remote id to do a PUT. If you have 3 users, PUTing to `/users/4.json` is perfectly legal. It's debatable whether this is replacing, but it's certainly not updating. PATCH to a non-existent resource will surely fail with a 404.

I'm going to close this pull request to allow for further discussion on an issue thread (or offline if you want over email). PATCH has become quite a small component in comparison and should be part of the larger discussion.

**Comment by dingbat** [comment]
Reopening - I think this is a fine place for discussion, and the rest of the thread is here already.
I am learning new things :) 

Just to be clear, when you say it's perfectly legal to PUT to `/users/4.json`, you're talking about the traditional HTTP standard, right? Rails controllers generated by scaffold (which is what NSRails is modeled after) invoke `update_attributes` in the "update" PUT request, which would make it illegal. To my understanding, the implementation will stay identical in Rails 4.0, just with the HTTP verb PATCH, right?

I am all for renaming `remoteUpdate` to `remotePatch` or similar. Of course, for now it would still make a PUT request, but use PATCH when Rails 4.0 is released. If your Rails app implements `update_attributes` on PATCH instead of PUT on the `:controller/:id` route (pre-4.0), then as per your PR, the verb for `remotePatch` could just be set in NSRConfig.

As I see it, `remoteReplace` would be unnecessary and possibly confusing. Yes, this would do a "placement" PUT, but at the moment it seems like Rails is incorrectly using PUT as PATCH, which would make it identical to `remotePatch`. And once again, I see no use for this method, even when implemented correctly. I'm curious - could you give an example of when replacing would be desired?

Does this sound good? Let me know if I'm misunderstanding something.

**Comment by scootklein** [comment]
Yes, I'm talking traditional HTTP and not Rails scaffolding. You make a good point, and it makes me wonder why the scaffold doesn't create the object if it can't find it by the primary key specified in the url.

The answer will likely lie in the philosophical direction this project wishes to head in. If it is beholden to the default scaffolding then the answer is to leave everything as is. If the change is made as suggested with `remoteUpdate` (PATCH) and `remoteReplace` (PUT) then it will theoretically work with both - users will need to modify their `update` methods in their controllers to some flavor of `find_or_create` should they wish to take advantage of that behavior.

Example: let's say you have user credentials for users' facebook, twitter, etc, accounts and you have a table to represent that. We'll call them `user` and `user_credentials` respectively. It's possible to nest the resource and make the primary key the type of credential it is so that you end up with resources as follows

```
/users/1/credentials/facebook.json
/users/1/credentials/twitter.json
```

In this case, the facebook credential may or may not be present, and you want to get rid of the previous one if it does indeed exist. A `PUT` operation is exactly what this situation calls for as it is a "create or update" operation with a primary key that is different than the auto_increment integer column. You can imagine there being a unique index on `user_id` and `type` for the `user_credentials` table to ensure that only 1 credential of each type can exist for each user.

**Comment by dingbat** [comment]
Sounds good.

`remoteUpdate` will adhere to whatever HTTP method is set in NSRConfig, and `remoteReplace` will always be PUT.

**Pull request closed without merging**
