### PR TITLE
allow OAuth token to be set in Authorization field

### PR DESCRIPTION
**Pull request by scootklein**
The OAuth 2 spec looks like it accepts the token in the Authorization header when prefixed with "OAuth " instead of "Basic ".

### CODE REVIEW

**Comment by dingbat** [comment]
This looks great, but I'm curious - is this all that's needed to get OAuth up and running? I'm not super-familiar with OAuth but I'm assuming this expects the client to make the validation request itself (with secret key, etc) and then simply set the access token in NSRConfig? Or does the webview confirmation do all of that for you and just provide the token?

I guess what I'm saying is, this looks half-baked right now. Let me know if that's not true though, and thanks for your contribution! Your PATCH commits looked good, they just seem to be tied to this one too, so I just want to get it sorted out before I merged.

**Comment by scootklein** [comment]
There are varying forms of OAuth, and this implementation would work with OAuth 2 where there is just 1 authentication token passed over ssl, and you're not required to do any signature hashing of the url and query params. Some other library will need to be used to obtain to authentication token before it is set in NSRails and subsequently passed as a header. In my case, I have an API endpoint to create a new authentication token ("logging in") either with a username/password or a facebook authentication token as obtained by the facebook SSO process.

## 

Scott Klein
http://www.scottkle.in

**Comment by dingbat** [comment]
Right, makes sense.

My only concern is that NSRails doesn't yet support SSL, so I'm not sure how I feel about letting a client pass the plainstring OAuth token in the header over just HTTP. I've been peeking over at RestKit to see how they implement SSL, but if you have expertise, feel free to contribute.

**Comment by scootklein** [comment]
NSURLRequest handles everything SSL for you. If the base url for the server is https it will be parsed as such and SSL will be established before anything is sent over the connection.

## 

Scott Klein
http://www.scottkle.in

**Pull request closed without merging**
