### PR TITLE
New default date format for Rails 4

### PR DESCRIPTION
**Pull request by pareeohnos**
The date format that rails 4 uses by default has changed so include fractions of a second.
This just fixes the default format being used by NSRails

### CODE REVIEW

**Comment by dingbat** [comment]
Hm, tests are failing, of course.

Trying to think of a way to update this that wouldn't break existing apps that talk to Rails 3.

Possibly a Rails version #define, or an NSRConfig setting. Will report back, feel free to leave feedback.

**Comment by pareeohnos** [comment]
Had a think but can't really think of any nicer ways of doing it other than a `#define` which could then also change the default update method to `PATCH` as is explained in `NSRConfig.h:241`

**Comment by ndonnellan** [comment]
Timezone information doesn't seem to transfer to NSDate if the Z is quoted (i.e. 'Z'). My configuration string for Rails 4 that seems to work is:

```
NSRConfig.defaultConfig.setDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ")
```

**Comment by dingbat** [comment]
Ok guys, thanks for your help.

I added a method in NSRConfig called `configureToRailsVersion:`, to which you can pass `NSRRailsVersion3` or `NSRRailsVersion4`. This will update both the update method and the date format (@ndonnellan's).

This is also now the default (which I'm sure will break existing apps -- so a warning gets printed if a Rails3-style date format is detected).

**Pull request closed without merging**
